### ISSUE TITLE
I get in error

### ISSUE THREAD

**Issue by fatihinstf** [dipanjanS/text-analytics-with-python#1]
my nltk is not complete download, because one of module is out of date. So, when i try your code i get in error, on of module is not work.

In [47]: from contractions import CONTRACTION_MAP
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-47-8a0530a24ce6> in <module>()
----> 1 from contractions import CONTRACTION_MAP

ImportError: No module named contractions

![image](https://cloud.githubusercontent.com/assets/22743585/25287695/92367cb4-26ec-11e7-8068-7ae95996f5a3.png)

**Comment by dipanjanS** [comment]
You need to have the contractions.py file in the same directory where you are running the code. This file in not dependant on nltk.

**Comment by fatihinstf** [comment]
Ok i will try, thx

Can i have your whatsapp number for asking later? tks

**Comment by dipanjanS** [comment]
I don't use Whatsapp really so you can email me in the address specified in my profile in case of any specific issues..
