### ISSUE TITLE
Non functioning code in chapter 7: sentiwordnet example

### ISSUE THREAD

**Issue by ruddjm** [dipanjanS/text-analytics-with-python#11]
This is also on page 356.

from nltk.corpus import sentiwordnet as swn

good = swn.senti_synsets('good', 'n')[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'filter' object is not subscriptable

**Comment by dipanjanS** [comment]
Python 3 has changed things you can try:

```
good = list(swn.senti_synsets('good', 'n'))[0]
```
