### ISSUE TITLE
Jupyter Notebooks for 2nd Edition?

### ISSUE THREAD

**Issue by pauldevos** [dipanjanS/text-analytics-with-python#12]
Hello Dipanjan,

I was wondering if you had the notebooks in question mentioned in the Safari/OReilly book available? The link led me here and I don't see them in the repo.

Thanks!

![Screen Shot 2020-01-29 at 12 57 13 PM](https://user-images.githubusercontent.com/6967308/73388005-0b948880-4297-11ea-8329-8bd166ccf596.png)

**Comment by dipanjanS** [comment]
Apologies had a long standing issue with the  code access and then fixing LFS issues. It is available now.
