### ISSUE TITLE
Bug in feature_extractors() (Chapter 4)

### ISSUE THREAD

**Issue by athoag** [dipanjanS/text-analytics-with-python#5]
Going through feature_extraction_demo.py, the line:

```python
avg_word_vec_features = averaged_word_vectorizer(corpus=TOKENIZED_CORPUS,
                                                 model=model,
                                                 num_features=10)
```
raises an AttributionError:
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-cdd908e72f5c> in <module>()
      2 TOKENIZED_CORPUS
      3 avg_word_vec_features = averaged_word_vectorizer(corpus=TOKENIZED_CORPUS,
----> 4                                                  model=model, num_features=10)

/Users/athair/researchdone/text_analytics_with_python/codes/feature_extractors.pyc in averaged_word_vectorizer(corpus, model, num_features)
     58 
     59 def averaged_word_vectorizer(corpus, model, num_features):
---> 60     vocabulary = set(model.index2word)
     61     features = [average_word_vectors(tokenized_sentence, model, vocabulary, num_features)
     62                     for tokenized_sentence in corpus]

AttributeError: 'Word2Vec' object has no attribute 'index2word'
```

with the latest gensim: v'3.0.1' 
I tried with both pip install gensim and from pulling directly from the gensim github repository: https://github.com/RaRe-Technologies/gensim/

The accepted answer here suggests a fix: https://stackoverflow.com/questions/43146077/index2word-in-gensims-doc2vec-raises-an-attribute-error

**Comment by dipanjanS** [comment]
@athoag Yep thanks to gensim's breaking changes with no backward compatibility this issue comes up. I had noticed this when working on a new book and had forgotten to change it for this one. 

Thanks for bringing this to my notice, I will be fixing this in a couple of weeks and expecting this to be also fixed in the revised edition of the book next year too.

**Comment by samuelxmli** [comment]
Can anyone advise how to fix this urgent problem while using Python 3 ?
"----> from normalization import normalize_corpus
import nltk
from operator import itemgetter

ModuleNotFoundError: No module named 'normalization' "

**Comment by YogeshSakpal** [comment]
HI Dipanjan,
Getting Error classification.py file for normalization
ModuleNotFoundError: No module named 'normalization'
