### ISSUE TITLE
ModuleNotFoundError: No module named 'normalization

### ISSUE THREAD

**Issue by samuelxmli** [dipanjanS/text-analytics-with-python#7]
Can anyone advise how to fix this urgent problem while using Python 3 ?
While I am trying the code in Chapter 4:
"----> from normalization import normalize_corpus
import nltk
from operator import itemgetter

ModuleNotFoundError: No module named 'normalization' "

**Comment by dipanjanS** [comment]
Guys please read the chapter when using the code or check __all__ the files for the chapter when running the code.

The `normalization` module is already present in the same directory in Chapter 4. You can find it here https://github.com/dipanjanS/text-analytics-with-python/blob/master/Chapter-4/normalization.py

**Comment by subbayya** [comment]
I get an error No module named markupbase

**Comment by subbayya** [comment]
I tried installing pattern and it gives me an error
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/61/y4p556855q588ywnn_mmsqdm0000gn/T/pip-install-a9em6a4v/mysqlclient/

**Comment by AngelAlvarado** [comment]
For whoever runs into this, if you are working with the second edition of the book use the file [/normalization.py](https://github.com/dipanjanS/text-analytics-with-python/blob/master/Chapter-4/normalization.py) from the old_version folder.
