### ISSUE TITLE
csv files are not able to downlod

### ISSUE THREAD

**Issue by pydv9991** [dipanjanS/text-analytics-with-python#8]
hi, 
Cloning your repository is not downloading the data files(csv files).

How to download csv files from your repo.

**Comment by dipanjanS** [comment]
This is a really bad issue with Git LFS I think. Give me a couple of days I will fix this and update on this thread

**Comment by WilliamWang1994** [comment]
I am expecting to hear good news

**Comment by dipanjanS** [comment]
I will be working on this today and this week, since I need to restructure this repository for the upcoming new version of this book (in Python 3.x). Expect an update soon for this and a fix too.

**Comment by dipanjanS** [comment]
This is fixed for now, let me know in case any further issues arise. Git LFS has been more of a hindrance than a help so I removed it. Will be working on the revised version of this book in the next few months.
